version: '3.8'

services:
  app:
    container_name: app-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    networks:
      - internal
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

networks:
  internal:
